version: '3.3'

services:
    piliverse-be:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: piliverse-be
      network_mode: "host"
      restart: unless-stopped
      
